### ISSUE TITLE
Can't correctly read event file with ::before tag

### ISSUE THREAD

**Issue by kleinpetr** [EndBug/version-check#129]
**Describe the bug**
I am trying to implement the simplest version check in this order
- We don't use semver yet
- for each PR I want to check package version against to target branch
- because I want to prevent our team to forget updating it

**To Reproduce**
```yml
      - name: Check version number 👀
        id: version_check
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          static-checking: localIsNew
          file-url: ::before

      - name: Check version number 👀
        if: steps.version_check.outputs.changed == 'false'
        run: |
          echo "No version change 🐞"
          exit 1
```

For the first commit to the PR I've got this error
`Error: Can't correctly read event file (before: undefined, repository: [object Object])`

**Expected behavior**
I expect pipeline to fail when the version is not updated

**Comment by EndBug** [comment]
Can you post a link to the actual action logs or, if the repo is private, a copy of the logs of the entire step that uses the action?

**Comment by kleinpetr** [comment]
just this

```
Run EndBug/version-check@v2
  with:
    token: ***
    static-checking: localIsNew
    file-url: ::before
Searching for version update...
Error: Can't correctly read event file (before: undefined, repository: [object Object])
```

**Comment by EndBug** [comment]
It seems like the action is able to parse the event file, but it doesn't contain a "before" tag...
Does this happen when you update the PR too?

**Comment by kleinpetr** [comment]
No with second and more commits it works. But within the first I would like to compare it with the target branch.

Anyway I want just make a check that developers manually updated the version before merge it.

**Comment by EndBug** [comment]
Oh, ok, I get it: in this case I think it would be better not to check against her previous commit, but against the base branch.
The current version of the action (a rewrite is needed, but I can't find the time to do it...) does not have a built-in way to do this, but you can use the [`github` context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context) to get the base ref and from that you can get you package file through the GitHub API.

`github.base_ref` should contain the ref of the base branch that is the target of the pull request. You can build the URL like this:

```
https://raw.githubusercontent.com/${{ github.repo }}/${{ github.base_ref }}/YOUR_PATH_TO_PACKAGE_FILE.JSON
```

So, recap:

```yaml
- name: Check version number 👀
   id: version_check
   uses: EndBug/version-check@v2
   with:
   token: ${{ secrets.GITHUB_TOKEN }}
   static-checking: localIsNew
   # Replace YOUR_PATH_TO_PACKAGE_FILE.JSON with the local path of your package file.
   file-url: https://raw.githubusercontent.com/${{ github.repo }}/${{ github.base_ref }}/YOUR_PATH_TO_PACKAGE_FILE.JSON

- name: Check version number 👀
  if: steps.version_check.outputs.changed == 'false'
  run: |
    echo "No version change 🐞"
    exit 1
```
