### ISSUE TITLE
[Bug] `file-name` private repo not working

### ISSUE THREAD

**Issue by AndrewOttavianoAbb** [EndBug/version-check#169]
**Describe the bug**
I'm working in a mono-repo (using Nx) in a github private account. I added the version-check action to my dev yml pipeline and realized I needed to specify which `package.json` I should use. So I provided the `file-name` attribute.

**To Reproduce**
Unfortunately, since the project is closed source, I can't include commit information. But here is my pipeline configuration
```yml
verify-version:
    needs: setup-node_modules
    runs-on: ubuntu-latest
    steps:
      - name: tell me the dir
        run: ls
      - name: Version Check
        uses: EndBug/version-check@v2.1.0
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-name: libs/core/package.json
      - name: Version Check Passed
        if: steps.check.outputs.changed == 'true' && contains(steps.check.outputs.version, 'alpha') == true
        run: 'echo "Publishing version: ${{ steps.check.outputs.version }}!"'
      - name: Version Check Failed - No alpha
        if: contains(steps.check.outputs.version, 'alpha') != true
        run: 'echo "Invalid version number! Must use the word "alpha" in version number. Received: ${{ steps.check.outputs.version }}.'
      - name: Version Check Failed - Not new version
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No new version (${{ steps.check.outputs.version }}), exiting" && exit 0'
```

My project is structured such that all the libraries are in the `libs` folder. So my file path is pretty simple: `libs/core/package.json`.
I tried adding a `.` on the front and that didn't seem to change anything.

This is the error message I'm getting:
```
Run EndBug/version-check@v[2](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:2).1.0
  with:
    token: ***
    file-name: libs/core/package.json
    diff-search: false
    github-api-url: https://api.github.com
  env:
    NODE_VERSION: 16.x
    NODE_AUTH_TOKEN: ***
Searching for version update...
(node:1[4](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:4)8[5](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:5))
UnhandledPromiseRejectionWarning: Error: Package file not found: libs/core/package.json
    at /home/runner/work/_actions/EndBug/version-check/v2.1.0/lib/index.js:1:1[6](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:6)5101
    at processTicksAndRejections (internal/process/task_queues.js:9[7](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:7):5)
(node:14[8](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:8)5) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:[14](https://github.com/escreengithub/arc/runs/6734147012?check_suite_focus=true#step:3:15)85) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Expected behavior**
I would expect the action to find my `package.json` and read the version correctly.

**Additional context**
I'm still kinda new to Github actions so I could have definitely not setup the action correctly. But it seems pretty straight forward. I appreciate any thoughts you have.

**Comment by EndBug** [comment]
Hi, the first thing that pops out to me is that you're running the job without checking out the repo: try adding a new steps that uses [`actions/checkout`](https://github.com/actions/checkout#usage):

```yaml
steps:
  - uses: actions/checkout@v3
  # ...
```
