### ISSUE TITLE
Error: Cannot read properties of undefined (reading '_links')

### ISSUE THREAD

**Issue by allenyummy** [EndBug/version-check#218]
Hello,

I used version_check in my GitHub action workflow, and encountered the problem below.
Does anyone face the same problem ?

<img width="938" alt="image" src="https://user-images.githubusercontent.com/36063123/233825231-fe959d7b-9916-4712-8a38-b55ee3e7453a.png">

**Comment by EndBug** [comment]
Hmm, that's weird, with what event are you using the actions?

**Comment by lkreimann** [comment]
I have this too :/

Using `actions/checkout@v3` in my workflow right before using this action and the event is `workflow_dispatch` for testing purposes

**Comment by ljukas** [comment]
Im getting this error too when using `workflow_call` to trigger my action

**Comment by EndBug** [comment]
Hey @ljukas, as mentioned above, 

> The solution would be using the `static-checking` input when running on workflow dispatch.

If you're having issues while doing that, feel free to let me know, maybe in a new issue so that we don't ping previous participants ;)

**Comment by lizozom** [comment]
@EndBug I'm seeing the same error when running the workflow locally using `act`.
Any tips?

**Comment by EndBug** [comment]
Hey @lizozom, have you tried the solution described above?
Using `act` may affect the action's behavior, as it's heavily based on the event that triggers the (normal) action run

**Comment by guillaume-docquier-vention** [comment]
Did we figure out how to make it work with `workflow_call`?
I'm getting `Error: Cannot read properties of undefined (reading '_links')`

```
name: Publish To NPM

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
    secrets:
      TOKEN:
        required: true

jobs:
  check-npm-version-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Check if NPM version has been updated
        uses: EndBug/version-check@v2
        id: version-check
        with:
          diff-search: true
          file-name: ${{ inputs.project-path }}/package.json
```
