### ISSUE TITLE
[Bug] Can't find version field

### ISSUE THREAD

**Issue by jfbrennan** [EndBug/version-check#237]
**Describe the bug**
Followed the readme, doesn't work. I get the following in the GH actions console:
```
Run EndBug/version-check@v2
  with:
    diff-search: true
    token: ***
    file-name: package.json
    github-api-url: https://api.github.com/
Searching for version update...
Error: Error: Can't find version field
Outputs:
  changed: false
/home/runner/work/_actions/EndBug/version-check/v2/lib/index.js:1
...
```
My package.json lives at the root of the project. It has `"version": "1.0.1"`

**To Reproduce**
My workflow:
```
name: Publish package

on:
  push:
    branches:
      - "main"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish package
        if: steps.check.outputs.changed == 'true'
        run: 'echo "New version. Publishing: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})" && npm publish'

      - name: No publish
        if: steps.check.outputs.changed == 'false'
        run: 'echo "No version change. Package will not be published."'
```

**Expected behavior**
I was expecting this to find the version in package.json and run the steps.
