### ISSUE TITLE
[Bug] Suddenly getting 403 after changing nothing

### ISSUE THREAD

**Issue by LukasDeco** [EndBug/version-check#310]
**Describe the bug**

```
- name: Check if version has been updated
        id: package-version-check
        uses: EndBug/version-check@v2
        with:
          file-name: ./packages/package-a/package.json
          token: ${{ secrets.GITHUB_TOKEN }}
```

Getting a 403 response even though I am passing in the token.

**To Reproduce**

can't share commit it's on private repo
```
with:
    file-name: ./packages/package-a/package.json
    token: ***
    diff-search: false
    github-api-url: https://api.github.com
Searching for version update...
Error: Response code 403(Forbidden)
```
**Expected behavior**
No 403 status code

**Screenshots**
N/A
**Additional context**
It was working just fine and then all of a sudden it stopped working on clear reason why
