### ISSUE TITLE
Building on windows-latest gives me error "Unsupported protocol"

### ISSUE THREAD

**Issue by LMS007** [EndBug/version-check#311]
```
jobs:
  build_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check if version has been updated
        uses: EndBug/version-check@v2
```

gives me this errror

```
Run EndBug/version-check@v2
  with:
    diff-search: false
    file-name: package.json
    token: ***
    github-api-url: https://api.github.com/
  env:
    GITHUB_TOKEN: ***
Searching for version update...
Error: Unsupported protocol "d:"
```

I'm not sure this is windows related, but I cant really see how my workflow could be the issue here
