### ISSUE TITLE
Private repo fails

### ISSUE THREAD

**Issue by sahellebusch** [EndBug/version-check#35]
Hey folks, trying to get this to work w/ a private org and wondering if y'all can help. I've tried numerous permutations and have tried v 1.1.0 through 2 and can't get it to work. For versions 1.6 and lower, if I use the diff-check, it'll throw a an error due to undefined length, likely due to empty commits for some reason. Everything above 1.6 breaks w/ a 404. Any guidance is appreciate. What I've got for now is below (which gives me the 404 error).

Thanks! 

```yml
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Check version bump
        uses: EndBug/version-check@v2.0.0 
        id: check
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true
      - name: Log when unchanged
        if: steps.check.outputs.changed == 'false'
        run: exit 1
```
