### ISSUE TITLE
[Bug] TypeError: Cannot read property 'id' of undefined (tagged commit with diff-search)

### ISSUE THREAD

**Issue by spinlud** [EndBug/version-check#36]
Hi there!
I have pushed a tagged commit and received the following error:

```
TypeError: Cannot read property 'id' of undefined
```

![image](https://user-images.githubusercontent.com/12783208/104127842-af6e2b80-5364-11eb-9738-00f3394af12a.png)

This is the commit: https://github.com/spinlud/sequelize-typescript-generator/commit/a0198e633f994801425f2b91b7f6c3c143c3cb7f

This is the action configuration:

```yml
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          diff-search: true

      - name: Publish
        if: steps.check.outputs.changed == 'true' && github.ref == 'refs/heads/master'
        run: |
          npm set registry "https://registry.npmjs.org"
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_PUBLISH_TOKEN }}
          npm publish
```

Any idea how to fix?
