### ISSUE TITLE
Version 2 fails with private repo [Bug]

### ISSUE THREAD

**Issue by goerwin** [EndBug/version-check#41]
**Describe the bug**
Using `EndBug/version-check@v2` throws a 404 when the repo is private

**To Reproduce**
Using this workflow:
```yml
name: release

on:
  push:
    branches: [master]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - id: check
        name: Verify package.json version change
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push new tag
        if: steps.check.outputs.changed == 'true'
        run: 'git tag v${{ steps.check.outputs.version }}'
```

**result logs**
![captura_2021-04-19_21_01_08](https://user-images.githubusercontent.com/1928211/115326092-54618700-a152-11eb-8853-79e71046272c.png)
